service: email-notification-service

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  environment:
    EMAIL_USER: ${env:EMAIL_USER}
    EMAIL_PASSWORD: ${env:EMAIL_PASSWORD}

functions:
  send_email:
    handler: handler.send_email
    events:
      - http:
          path: notify
          method: post

plugins:
  - serverless-offline
