service: hms-email
provider:
  name: aws
  runtime: python3.9
functions:
  send-email:
    handler: handler.send_email
    events: [{http: {path: send-email, method: post}}]
plugins: [serverless-offline]